language: minimal
sudo: required
services:
  - docker

before_install:
  - docker build -t roohhiit110393/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roohhiit110393/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-926663231228"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
